---
title: "Cambios de vegetación"
author: "Ulises Hoil - Ecodata"
format: dashboard
editor: visual
---

```{r}
#| message: false
#| warning: false
#| include: false
library(sf)
library(terra)
library(mapgl)
library(shiny)
library(ggplot2)
library(ggspatial)


ndvi2017 <- terra::rast("Mid/ndvi_2017_cortado.tif")
ndvi2020 <- terra::rast("Mid/ndvi2020_cortado.tif")
ndvi2024 <- terra::rast("Mid/ndvi2024_cortado.tif")
cambios <- terra::rast("Mid/NDVI_negativo.tif")
merida<-st_read("Mid/Merida.geojson")


coloresverdes <- rev(c(
  "#00541B",  # verde muy oscuro
  "#1B7837",  # verde bosque
  "#4DAF4A",  # verde medio
  "#7FBC41",  # verde lima
  "#B8E186",  # verde paste  
  "#FFFFFF"  # blanco
))

coloresmag <- colorRampPalette(c("#000000", "#FF0000"))(10)


```

```{r}
#| message: false
#| warning: false
#| include: false
m1 <- maplibre(zoom = 9, center = c(-89.617, 20.967)) |>
  add_image_source(
    id             = "2017",
    data         = ndvi2017,
    colors         =coloresverdes ) |>
  add_raster_layer(
    id             = "2017",
    source         = "2017",
    raster_opacity = 0.8)

m2 <- maplibre(zoom = 9, center = c(-89.617, 20.967)) |>
  add_image_source(
    id             = "2024",
    data         = ndvi2024,
    colors         = coloresverdes) |>
  add_raster_layer(
    id             = "2024",
    source         = "2024",
    raster_opacity = 0.8)

mapacomparadoveg <- mapgl::compare(m1, m2)

```

# Cambios 2017 - 2024

```{r}
mapacomparadoveg
```

# Cambios

```{r}
cam <-maplibre(zoom = 9, center = c(-89.617, 20.967)) |>
  add_image_source(
    id             = "cambios",
    data         = cambios,
    colors         = coloresmag) |>
  add_raster_layer(
    id             = "cambios",
    source         = "cambios",
    raster_opacity = 0.8)

cam

```

# Temperaturas Dia y noche

```{r}
#| message: false
#| warning: false
#| include: false

tempdia<-terra::rast("Mid/Dia_2023.tif")
tempnoche <- terra::rast("Mid/Noche_2023.tif")

## paleta de colores de temperatura azul mas bajo rojo mas caliente
colorestemp <- colorRampPalette(c("#0000FF", "#FFFFFF", "#FF0000"))(10)

```


```{r}
#| message: false
#| warning: false
#| include: false
m1temp <- maplibre(zoom = 9, center = c(-89.617, 20.967)) |>
  add_image_source(
    id             = "2023",
    data         = tempdia,
    colors         =colorestemp ) |>
  add_raster_layer(
    id             = "2023",
    source         = "2023",
    raster_opacity = 0.9)

m2noche <- maplibre(zoom = 9, center = c(-89.617, 20.967)) |>
  add_image_source(
    id             = "2023",
    data         = tempnoche,
    colors         = colorestemp) |>
  add_raster_layer(
    id             = "2023",
    source         = "2023",
    raster_opacity = 0.9)

mapacomparatemp <- mapgl::compare(m1temp, m2noche)
```


```{r}
mapacomparatemp
```

